### ISSUE TITLE
Time is in the future

### ISSUE THREAD

**Issue by 4Eye** [hootnot/oanda-api-v20#103]
Hi hootnot,

I have recently been getting the following error from the wrapper:

ERROR : 12/10/2017 12:34:57 PM : {"errorMessage":"Invalid value specified for 'to'. Time is in the future"}

My code for getting the 'to':

```python
now = datetime.datetime.utcnow().isoformat('T')+'Z'
now = str(now[:-8] + 'Z')
```
I did notice you fixed this issue in version 0.4.2 - Am I doing something I shouldnt?

Thanks again so much!

**Comment by 4Eye** [comment]
Just to add - I changed my computers time -1 minute and it ran. Possibly a system/time issue at my end?

**Comment by hootnot** [comment]
Hi 4Eye,

before I look in code: there should no need to pass 'now'. only 'from' will do if you want up to 'now'.
If you still get the error after removing your 'now', pls. provide me the piece of code and I will check on things

**Comment by 4Eye** [comment]
I see. I'll give that a go. Thanks again for the swift response! I'll report back shortly.

**Comment by 4Eye** [comment]
Works fine. Thanks again dude!

**Comment by hootnot** [comment]
... then I will close this one
