### ISSUE TITLE
bidask historical data

### ISSUE THREAD

**Issue by tarjoadi** [hootnot/oanda-api-v20#124]
hi,

is it possible to get the bid-ask data for the historical calls?

Thank you

**Comment by hootnot** [comment]
Hi, the oanda-api-v20 (oandapyV20) allows to do all the v20 interface supports. So the answer is to find in the OANDA docs: http://developer.oanda.com/rest-live-v20/instrument-ep/

You can see here that you can request Mid, Bid, Ask. So yes, you can get bid/ask on historical data up to the granularity of 5 seconds (S5). 

You can't get historical tickdata as you get via the streaming quotes though.

**Comment by tarjoadi** [comment]
Hi,
Thank you for the answer.
Am I able to access the API with the Trial account?
Thank you,Adrian Tarjoianu
    On Saturday, June 2, 2018, 1:13:36 PM EDT, Feite Brekeveld <notifications@github.com> wrote:  
 
 
Hi, the oanda-api-v20 (oandapyV20) allows to do all the v20 interface supports. So the answer is to find in the OANDA docs: http://developer.oanda.com/rest-live-v20/instrument-ep/

You can see here that you can request Mid, Bid, Ask. So yes, you can get bid/ask on historical data up to the granularity of 5 seconds (S5).

You can't get historical tickdata as you get via the streaming quotes though.

**Comment by hootnot** [comment]
Yes, API can be accessed with both trial and live account. You have a fully equivalent environment.
