### ISSUE TITLE
Setting `expiry` on LimitOrderRequest

### ISSUE THREAD

**Issue by trevorwelch** [hootnot/oanda-api-v20#125]
Hi all,

I'm trying to figure out how to place an expiry date on all the limit orders I place. 

Has anyone had any luck with this? I don't see anything in the documentation about it. 

Thanks for your reply.

**Comment by hootnot** [comment]
Hi,

All documentation on the V20 REST API is found on developer.oanda.com.  The oandapyV20 library supports all parameters you find in the docs.

So, regarding your specfic question: http://developer.oanda.com/rest-live-v20/order-df/#OrderRequest gives details on order requests. 

You shoud use *timeInForce* and set it to *GTD* and you pass *gtdTime* with a date assigned where you want it to expire.

**Comment by hootnot** [comment]
Hi,

I've added some examples to the jupyter notebooks: https://github.com/hootnot/oanda-api-v20/blob/master/jupyter/orders.ipynb.

It covers:

  + placing a LimitOrder with GTD
  + canceling the LimitOrder
