### ISSUE TITLE
Insufficient authorization to perform request

### ISSUE THREAD

**Issue by saeedesmaili** [hootnot/oanda-api-v20#129]
I've cloned [this jupyter notebook file](https://github.com/benjaminchodroff/oandamomentum/blob/master/oandamomentumv20.ipynb), but running the following snippet leads to an error:

```
import configparser

# v20 OANDA API - 3rd party
import json
from oandapyV20 import API    # the client
import oandapyV20.endpoints.trades as trades

config = configparser.ConfigParser()
config.read('oanda.cfg')

client = API(environment='practice',access_token=config['oanda']['access_token'])

import datetime
from dateutil import parser
import oandapyV20.endpoints.instruments as instruments

params={"from": parser.parse("2016-12-07 18:00:00 EDT").strftime('%s'),
        "to": parser.parse("2016-12-10 00:000:00 EDT").strftime('%s'),
        "granularity":'M1',
        "price":'A'}
r = instruments.InstrumentsCandles(instrument="EUR_USD",params=params)
data = client.request(r)
print(json.dumps(data, indent=2))    # <----- add this line to show the data
```

> V20Error: {"errorMessage":"Insufficient authorization to perform request."}

My access token is correct and works fine with v1 api.

**Comment by hootnot** [comment]
your v1 account looks like: 1234567, the v20 account looks like: 123-456-123456.

If you did use the correct account then you should revoke the token and generate a new one. 
If you don't have a v20 test account, get one ... and regenerate that token right away .

Then try again.

**Comment by hootnot** [comment]
@saeedesmaili  by coincidence I saw you also opened the same issue at https://github.com/benjaminchodroff/oandamomentum/issues/3, which was actually the right place since it concerns his repo. Pls. close that issue since there is no need to waste someones time on an already resolved issue. Next time pls. only open an issue once.

**Comment by saeedesmaili** [comment]
Thanks for your help and advice. I closed that issue.
