### ISSUE TITLE
instruments.InstrumentsOrderBook fails for some instruments

### ISSUE THREAD

**Issue by illi4** [hootnot/oanda-api-v20#132]
When I try to call instruments.InstrumentsOrderBook, it does not work for many instruments(for example 'NAS100_USD' or 'SPX500_USD'). The error message is "NAS100_USD is not a valid instrument". 
All the other endpoints work fine.  The code snippet I am using is: 

```
request = instruments.InstrumentsOrderBook(instrument = "NAS100_USD") 
orderbook = client.request(request)
```

How could this be fixed? Just in case, I tried calling instruments.InstrumentsOrderBook with instrument by name (instrument = "US Nas 100"), but this of course does not work as well.

**Comment by hootnot** [comment]
@illi4 Hi, I'll close this issue. I you asked the question at OANDA and the gave you and answer pls. write it here also. It might be helpful for others.

**Comment by illi4** [comment]
Indeed OANDA responded that orderbook is not enabled for some instruments including stock indices
