### ISSUE TITLE
I tested the API but error

### ISSUE THREAD

**Issue by 5harever** [hootnot/oanda-api-v20#135]
Please help me fix the problem.
I tried below code

# get a list of trades
from oandapyV20 import API
import oandapyV20.endpoints.trades as trades

api = API(access_token="blah blah blah")
accountID = "001-011-1926632-001"

r = trades.TradesList(accountID)
# show the endpoint as it is constructed for this call
print("REQUEST:{}".format(r))
rv = api.request(r)
print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))

And I got this error message.

REQUEST:v3/accounts/001-011-1926632-001/trades
---------------------------------------------------------------------------
V20Error                                  Traceback (most recent call last)
<ipython-input-2-662ea9b0e6e0> in <module>()
      9 # show the endpoint as it is constructed for this call
     10 print("REQUEST:{}".format(r))
---> 11 rv = api.request(r)
     12 print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))

~\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in request(self, endpoint)
    304 
    305             response = self.__request(method, url,
--> 306                                       request_args, headers=headers)
    307             content = response.content.decode('utf-8')
    308             content = json.loads(content)

~\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in __request(self, method, url, request_args, headers, stream)
    241                          response.content.decode('utf-8'))
    242             raise V20Error(response.status_code,
--> 243                            response.content.decode('utf-8'))
    244         return response
    245 

V20Error: {"errorMessage":"Insufficient authorization to perform request."}

**Comment by hootnot** [comment]
Hi @5harever , the error is very clear: V20Error: {"errorMessage":"Insufficient authorization to perform request."}, make sure that you use a correct token. Maybe just revoke it and generate a new one.

If you have both a live and a practice account make sure you don't mix up

**Comment by 5harever** [comment]
I already revoked and copy and paste again.
It was still same error.
I never created the practice version.

Or I have to define below?
class oandapyV20.API(access_token, environment='live', headers=None, request_params=None)

**Comment by hootnot** [comment]
if you want to use a live account AND you have a token for live, the code from your first message should be:

```api = API(access_token="blah blah blah", environment='live')```

By default the client works on the *practice* environment. So if you passed a token for a live-account that V20 authorization error was logical.

I would strongly advise you to work on the practice environment first.

**Comment by 5harever** [comment]
Oh this one is crystal clear.
Thank you very much.

Best Regards,

Mr. Patchara Wattanadheerakul (Share)
