### ISSUE TITLE
Direction of the trade is not available

### ISSUE THREAD

**Issue by 98thpixel** [hootnot/oanda-api-v20#136]
Thanks for the amazing library.

However, I just ran the sample code for fetching the list of open trades and noticed that the response does not include the direction of the trade (i.e BUY or SELL).

Is this how it is supposed to be or a bug? 
Are there any other workarounds to find whether a trade is a sell trade or a buy trade?

**Comment by hootnot** [comment]
it is pretty simple: a negative number of units is a short position, positive is long. See: https://github.com/hootnot/oandapyV20-examples/blob/master/src/market_orders_requests.py, it shows how to place a market order LONG. If you change the units to -100 it will be a SHORT order.

If you are LONG 100 and you place a SHORT order -200 you will end up with a net SHORT of -100. (asuming hedging is not activated)

So, this is not a bug, checkout the docs of oanda too: developer.oanda.com
