### ISSUE TITLE
import error.

### ISSUE THREAD

**Issue by najeex** [hootnot/oanda-api-v20#138]
**yes i am facing import error....**

` (oan) najeeb@najeeb:~/Music/repo/oandapyV20-examples/src$ pip install oandapyV20
Collecting oandapyV20
  Using cached https://files.pythonhosted.org/packages/0d/d5/f69c978f485db3048886c447398e39c6ec18041e689656e6d31697ea4e7f/oandapyV20-0.6.3.tar.gz
Building wheels for collected packages: oandapyV20
  Running setup.py bdist_wheel for oandapyV20 ... done
  Stored in directory: /home/najeeb/.cache/pip/wheels/2c/b0/cd/49054320a6cc51db0ff4f1ee15d8840375f16cef57b81ebfc0
Successfully built oandapyV20
Installing collected packages: oandapyV20
Successfully installed oandapyV20-0.6.3
`

`(oan) najeeb@najeeb:~$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

 In [1]: import oandapyV20
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bd2b0543a268> in <module>()
----> 1 import oandapyV20

ModuleNotFoundError: No module named 'oandapyV20'

In [2]: 
`

**Comment by hootnot** [comment]
I think you installed oandapyV20 as a python2 package.

If you simply start python2.7 I guess you can do the import. To get it available under python3 use pip3

**Comment by najeex** [comment]
no this is not working

**Comment by hootnot** [comment]
that is a comment worth nothing.
Did you run:
```pip3 install oandapyV20```
 also ?

You have an environment problem on your system related to the python version you (want to) use.

you can find where it is installed by running:

```locate oandapyV20.py | grep site```, you will get something like:

```
.../lib/python???/site-packages
```
