### ISSUE TITLE
live account

### ISSUE THREAD

**Issue by mreza12** [hootnot/oanda-api-v20#141]
Hi,
I can connect successfully to practice account , can not authenticate with live account.

How i can define endpoint for api call to be live account not practice account?
Thanks

**Comment by hootnot** [comment]
Hi, it's all in the docs: https://oanda-api-v20.readthedocs.io/en/latest/oanda-api-v20.html#the-client

default env is *practice*. When you want to use the live environment pass *environment='live'* when creating the API instance
