### ISSUE TITLE
param for openTrade 

### ISSUE THREAD

**Issue by haegwan** [hootnot/oanda-api-v20#146]
Hello,

After reading the doc and Oanda doc (https://developer.oanda.com/rest-live-v20/trade-ep/) it seems you cannot param filter by openTrade time?

something like below

params = {
"state":"CLOSED",
'to': '2019-06-25T08:00:00Z',
'from': '2019-06-01T00:00:00Z',
}

I'd like to get closed orders in a speicif date range to analyze performance.
Also checked up transaction endpoint but seems it has no answer neither. 

Thanks!

**Comment by hootnot** [comment]
Hi,

the `/v3/accounts{accountID}/trades/` endpoint allows queries by `id` and a list of `ids`.

I don't know how you designed your code, but every time you place an order you get a response holding the transaction ID also. So, you could pass a list of the ids you have (in case you save these)

The way I do it:
It is pretty easy to download all transactions with a few lines of code. Then load it in Pandas from a Jupyter notebook.
Pandas offers you all the manipulation you want and will save you a huge amount of time.
