### ISSUE TITLE
Short Order failed to work

### ISSUE THREAD

**Issue by peironggg** [hootnot/oanda-api-v20#151]
Thank you for the awesome work.

I understand we change the units from 100 to -100 when we want to create a short order. I did so on your MarketOrderRequest example and Oanda managed to open the trade. However, it was closed immediately due to what I presume is an error. This 'immediate closing' problem repeats itself without fail for short orders but not for long orders. May I know if you face a similar issue? Thank you.

**Comment by hootnot** [comment]
Hi,
Just a description of a problem doesn't give much info.

But the error you got from OANDA tell's you probably that you have some issue with your price.
