### ISSUE TITLE
make edit on readme

### ISSUE THREAD

**Issue by popeel2** [hootnot/oanda-api-v20#152]
additional instructions should be provided on the readme regarding adding negative units for sell orders && it would be important to explain (for beginners) that on a sell order the stop loss needs to be higher than the current price and take profit needs to be less than current price.  

Very unclear for beginners, the oanda rest 20 states that a side parameter needs to be passed but the logic here is different. sorry about sounding petty. 
![request](https://user-images.githubusercontent.com/1297833/62313249-4ccdec00-b45e-11e9-969c-33f53124ec96.PNG)

**Comment by hootnot** [comment]
Hi,

The documentation of the oanda-api-v20 library refers for details to the REST V20 docs. of OANDA. So, for details you always should look there.
Regarding your short order: http://developer.oanda.com/rest-live-v20/order-ep/ gives an example of a short order. I gave an example  also explaining  how to use the `contrib.requests` . 

It is obvious that you need to choose the right side for TP and SL orders. Maybe you should try to do some trading via the web-application first. It will provide you a better understanding in general.

You definitely should not trade by code if you don't understand this fully. Those who understand don' t have the questions/remarks you have regarding the TP and SL.
Docs are also clear: https://oanda-api-v20.readthedocs.io/en/latest/contrib/orders/marketorderrequest.html

Trading by code is not something I would recommend for beginners! Make sure you realize what you are doing. 

Therefore: I will not make that edit
