### ISSUE TITLE
The v1 orderbook_data endpoint has been disabled.

### ISSUE THREAD

**Issue by msarm** [hootnot/oanda-api-v20#156]
Will there be any update to support v20-REST for orderbook data ?

> "The v1 orderbook_data endpoint has been disabled. It has been replaced by the orderBook and positionBook endpoints in the v20-REST API.

**Comment by hootnot** [comment]
Guess you look for: https://oanda-api-v20.readthedocs.io/en/latest/endpoints/instruments.html ?

**Comment by msarm** [comment]
Thank you for clarifying.
