### ISSUE TITLE
Connection error.

### ISSUE THREAD

**Issue by JAB64** [hootnot/oanda-api-v20#157]
Sorry to ask a simple question but I've been working on for a few weeks with no success.  I get the follow error "TypeError: __init__() takes 1 positional argument but 2 were given" with the following code.  Thank you.

```
import json
from oandapyV20 import API    # the client
import oandapyV20.endpoints.trades as trades

access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
accountID = "xxx-xxx-xxxxxx-xxx"
client = API(access_token=access_token)

# request trades list
r = trades.TradesList(accountID)
rv = client.request(r)
print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))
```

**Comment by hootnot** [comment]
Works fine on my side. Please check what you posted here and what you run
