### ISSUE TITLE
API Timeout

### ISSUE THREAD

**Issue by vinitshetty** [hootnot/oanda-api-v20#161]
Hi, Is there a way to configure API timeout? I am trying to pull candle stick data every 5 mins. and it just freezes after some time and no exception thrown.

**Comment by vinitshetty** [comment]
Sorry figured it out -
api = oandapyV20.API(access_token=access_token,request_params={"timeout": 30})

**Comment by hootnot** [comment]
Hi, pls. also note that OANDA might have services down during weekend hours,
