### ISSUE TITLE
Setting take profit and stop loss

### ISSUE THREAD

**Issue by turbonerd123** [hootnot/oanda-api-v20#164]
I was wondering if anyone knew how to set the current market price to a variable. That way I can make the stop loss value something like price+0.001.

**Comment by hootnot** [comment]
it is all in the docs, see for instance: https://developer.oanda.com/rest-live-v20/order-df/#OrderRequest 

and oandapyV20: https://oanda-api-v20.readthedocs.io/en/latest/contrib/orders/stoplossorderrequest.html

Pls. drop this kind of question on stackoverflow (or alike). Github is for issues and not for support. This clearly is not an issue.
