### ISSUE TITLE
Trades or Orders count larger than 500

### ISSUE THREAD

**Issue by Zouuup** [hootnot/oanda-api-v20#166]
Hi! 

Thanks for the efforts, 

What will happen if I have more than 500 trades or orders?

ps: Oanda base API has a limit of default 50 and max of 500.

**Comment by hootnot** [comment]
Pls check the OANDA docs. for  ananswer to that kind of question.

**Comment by Zouuup** [comment]
Hi @hootnot !

Thanks for the prompt reply, Oanda API doc suggest to use a "count" parameter which (as far as I can see) is not implemented on the wrapper, any ideas?

**Comment by hootnot** [comment]
Everything is supported! Pls have a look at the documentation. All API-endpoint request classes are setup this way:
- parameters in the URL (likely required and taken as arguments )
- data to be sent (a.k.a. order spec. passed as data via the data argument)
- params to be sent (optional or required parameters sent via  the params argument)

The *count* parameter you refer to is probably one to be sent as:

```python
     params = {
         "count": 500
     }
     somerequestclass(..., params=params)
```

The README contains examples, the jupyter noterbooks show examples and the oandapyv2-examples repo shows lots of examples pointing out how to deal with *data*, *params* and *required parameters*

**Comment by Zouuup** [comment]
Thanks!
