### ISSUE TITLE
oanda-api-v20/oandapyV20/endpoints/pricing.py - STREAM example does not work.

### ISSUE THREAD

**Issue by biomechman** [hootnot/oanda-api-v20#168]
Would someone be able to provide a sample code with PriceStream() working on Python for the v20?

The example provided on lines 100-112 of the git and website makes absolutely no sense. 
  The 'print' statement is still from Python 2.7
  The way 'params' is coded give an incorrect syntax error because of the way the brackets are open.

When those are fixed and the example is ran, it returns: "TypeError: 'PricingStream' object is not iterable"

Here's the sample code as provided on (https://oanda-api-v20.readthedocs.io/en/latest/endpoints/pricing/pricingstream.html) and in this GitHub. The syntax errors were fixed, but it still doesn't work.

Cheers

```
import oandapyV20  
from oandapyV20 import API  
import oandapyV20.endpoints.pricing as pricing  
accountID = "..."  
api = API(access_token="...")  
params = {"instruments": "EUR_USD,EUR_JPY"}  
r = pricing.PricingStream(accountID=accountID, params=params)  
rv = api.request(r)  
maxrecs = 100  
for ticks in r:
    print(json.dumps(R, indent=4),",")
    if maxrecs == 0:
       r.terminate("maxrecs records received")
```

**Comment by oeyvindds** [comment]
Try this one:

import os
import argparse
import json
from oandapyV20 import API
from oandapyV20.endpoints.pricing import PricingStream


class Streaming:
    """Script for streaming of rates
    Example use: streaming.py --inst EUR_USD --inst EUR_JPY
    Can be one or more instruments
    Will keep going until stopped or error occurs
    """

    # Get credentials from .env
    access_token = os.getenv("TOKEN")
    accountID = os.getenv("ACCOUNT_ID")

    # Parser for tickers
    parser = argparse.ArgumentParser(prog="streaming")
    parser.add_argument("function", type=str, action="store", nargs=1)
    parser.add_argument("-i", "--instruments", type=str, action="append")
    args = parser.parse_args()

    # Generate for the api-calls
    api = API(
        access_token=access_token, environment=os.getenv("OandaEnv"), request_params={}
    )

    r = PricingStream(
        accountID=accountID, params={"instruments": ",".join(args.instruments)}
    )

    # Continious streaming of rates
    while True:
        try:
            for R in api.request(r):
                R = json.dumps(R)
                print(R)

        except Exception as e:
            print("Error occured: {}\n".format(e))
            break

Should work flawless with Python 3.7
