### ISSUE TITLE
{"errorMessage":"Missing JSON body"} error response in TradeClose

### ISSUE THREAD

**Issue by bestoak** [hootnot/oanda-api-v20#172]
Every time i call trades.TradeClose, below error occurs.
It works fine last week, but happened all the time since today.
Does anyone have same problem or how can i solve this issue?

`File "/usr/local/lib/python3.8/site-packages/oandapyV20/oandapyV20.py", line 305, in request
    response = self.__request(method, url,
  File "/usr/local/lib/python3.8/site-packages/oandapyV20/oandapyV20.py", line 243, in __request
    raise V20Error(response.status_code,
oandapyV20.exceptions.V20Error: {"errorMessage":"Missing JSON body"}`

**Comment by hootnot** [comment]
Hi, please show the code

**Comment by bestoak** [comment]
I did nothing, and it now works.....
I think it's something wrong with oanda server side.
Anyway, Thank you very much for your response.
Please let me close this issue.

**Comment by hootnot** [comment]
if it appears again, check your data parameter. It probably has a value other than None and not a dict with the correct values.
