### ISSUE TITLE
Streaming OHLC data?

### ISSUE THREAD

**Issue by sword134** [hootnot/oanda-api-v20#178]
Hello,
Is there a way to get the Open, High, Low, Close data through a stream? Right now the pricing stream only passes bids and asks.

**Comment by hootnot** [comment]
Hi,
bid/ask that is the definition of a stream :-) 
By adding a time frame you get OHLC for that time frame.
You can do 2 things:
- process a stream and fabricate OHLC records from it (check: https://github.com/hootnot/oanda-trading-environment)
- request candles of your choice from OANDA, it will give you the completed records and for the last record it will flag the record is completed=False, see: https://oanda-api-v20.readthedocs.io/en/latest/endpoints/instruments/instrumentlist.html#   If you would  request an M1 candle every 15 seconds for EUR_USD, you will get (likely) 3 times an incomplete candle and when it is completed you get the completed one + the new one that is incomplete.

**Comment by sword134** [comment]
@hootnot Thank you for the reply. If I use completed=False on M5 candles and want to fetch new data every say 2 seconds on 11 instruments, would that get my API key restricted?

**Comment by hootnot** [comment]
check: https://developer.oanda.com/rest-live-v20/development-guide/ for details

every 2 seconds on 11 instruments should be no problem with 120 requests / second allowed
