### ISSUE TITLE
Unit not accepting less than 1

### ISSUE THREAD

**Issue by cruizytrader** [hootnot/oanda-api-v20#183]
BTC_USD was recently changed to accept micro units and 0.01 being the smallest by Oanda and removed the instrument MBTC_USD.
There is now an error with an order made because it seems not to allow units less than 1.
Please assist. John

**Comment by hootnot** [comment]
Fixed: the Units now accept integer, float with 1 decimal and float with 2 decimals

**Comment by cruizytrader** [comment]
Terrific. Thanks
