### ISSUE TITLE
Proxy uses HTTP and not HTTPS

### ISSUE THREAD

**Issue by QuanTurtle-founder** [hootnot/oanda-api-v20#191]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='[stream-fxpractice.oanda.com](http://stream-fxpractice.oanda.com/)', port=443)
Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:852)

**Comment by hootnot** [comment]
Sounds like you need to check your proxy config
