### ISSUE TITLE
Errors in Code

### ISSUE THREAD

**Issue by WestonShakespear** [hootnot/oanda-api-v20#20]
In the second example in your README file there are two syntax mistakes in the code. Line 15 and 20 are missing another closing parentheses.

**Comment by hootnot** [comment]
Thx! Fixed them.

**Comment by WestonShakespear** [comment]
No problem, so where is the documentation for your package? Some of the
link give me a 404. I found the examples in streaming rates and historic
prices. Do you have any pics or examples an actually placing trades?
