### ISSUE TITLE
PricingStream is not working 

### ISSUE THREAD

**Issue by msh855** [hootnot/oanda-api-v20#215]
Hi, 

This example from your documentation is not working: 
```

>>> r = pricing.PricingStream(accountID=accountID, params=params)
>>> rv = api.request(r)
>>> maxrecs = 100
>>> for ticks in r:
>>>     print json.dumps(R, indent=4),","
>>>     if maxrecs == 0:
>>>         r.terminate("maxrecs records received")
```

I get this error: `'PricingStream' object is not iterable `

Here what I am doing: 

```
cross = 'USD_JPY'
r = pricing.PricingStream(accountID=account_id, params={"instruments": cross})
rv = api.request(r)
```

**Comment by hootnot** [comment]
Indeed, the request object is not iterable, the result of the client request of the object is

https://github.com/hootnot/oandapyV20-examples/blob/master/src/streaming_prices.py

```
for ticks in rv:   # not r !
```

**Comment by msh855** [comment]
Got it. I think the documentation needs to change as well. Possibly it is a typo, but needs to be fixed.
