### ISSUE TITLE
neworder.py syntax issue

### ISSUE THREAD

**Issue by WestonShakespear** [hootnot/oanda-api-v20#25]
Line 35 is currently: "api = API(access_token=token)" but it should be: "api = API(access_token=token, headers={"Content-Type": "application/json"})

It also might be a good idea to add: "environment="practice"" so that if somebody executed this program and doesn't notice that it is in a live environment they don't get financially hurt.

**Comment by hootnot** [comment]
the header is set automatically since #18 , so it is not needed on the client anymore.

"environment='practice'"  by default. If you want to access 'live' you need to pass it explicitely

So there is no issue here
