### ISSUE TITLE
Issue with sending requests

### ISSUE THREAD

**Issue by kevinwong15** [hootnot/oanda-api-v20#68]
Hi,

I am new to Python and I am getting the following error  when sending a request through the wrapper. Can you walk me through how I can diagnose the problem? 

Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    rv = api.request(r)
  File "C:\Python36\lib\site-packages\oandapyV20\oandapyV20.py", line 306, in request
    request_args, headers=headers)
  File "C:\Python36\lib\site-packages\oandapyV20\oandapyV20.py", line 243, in __request
    response.content.decode('utf-8'))
oandapyV20.exceptions.V20Error

I ran the following codes;

access_token = "My own token"
client = API(access_token=access_token)
r = accounts.AccountList()
response = client.request(r)

**Comment by hootnot** [comment]
@kevinwong15 please show the full code you ran

**Comment by almanshow** [comment]
Hello,

I have kind of the same problem:
I ran: 

# get a list of trades
from oandapyV20 import API
import oandapyV20.endpoints.trades as trades
api = API(access_token="mytokenhere")
accountID = "myIDhere"
r = trades.TradesList(accountID)
# show the endpoint as it is constructed for this call
print("REQUEST:{}".format(r))
rv = api.request(r)
print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))

And I have the following response: 

REQUEST:v3/accounts/myaccount/trades
---------------------------------------------------------------------------
V20Error                                  Traceback (most recent call last)
<ipython-input-20-9274ba42aafd> in <module>()
      7 # show the endpoint as it is constructed for this call
      8 print("REQUEST:{}".format(r))
----> 9 rv = api.request(r)
     10 print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))

C:\Users\user\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in request(self, endpoint)
    304 
    305             response = self.__request(method, url,
--> 306                                       request_args, headers=headers)
    307             content = response.content.decode('utf-8')
    308             content = json.loads(content)

C:\Users\user\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in __request(self, method, url, request_args, headers, stream)
    241                          response.content.decode('utf-8'))
    242             raise V20Error(response.status_code,
--> 243                            response.content.decode('utf-8'))
    244         return response
    245 

V20Error:

**Comment by hootnot** [comment]
@almanshow missing in your code:
```python
import json
```

I have no trouble running your piece of code:

```python
import json
from oandapyV20 import API
import oandapyV20.endpoints.trades as trades
api = API(access_token="...")
accountID = "xxx-yyy-zzzzzz-abc"   # make sure this is a V20 account! and not a v1 account: 1234567
r = trades.TradesList(accountID)

print("REQUEST:{}".format(r))
rv = api.request(r)
print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))
```
Gives:

```json

REQUEST:v3/accounts/xxx-yyy-zzzzzz-abc/trades
RESPONSE:
{
  "trades": [], 
  "lastTransactionID": "7775"
}
```
@kevinwong15 @almanshow : do you have a V20 token / account ? 
If not please create the V20 account and regenerate a new token.

**Comment by almanshow** [comment]
Hello,

Thank you for helping me.
I am sure I have a V20 account and even importing json I still get the same error message. 

What could be the problem?

**Comment by hootnot** [comment]
Wrap the request in a try/except:

```python
import json
from oandapyV20 import API
import oandapyV20.endpoints.trades as trades
api = API(access_token="...")
accountID = "xxx-yyy-zzzzzz-abc"   # make sure this is a V20 account! and not a v1 account: 1234567
r = trades.TradesList(accountID)

print("REQUEST:{}".format(r))
try:
    rv = api.request(r)
except V20Error as err:
    print("ERROR: {}".format(err))
else:
    print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))
```

**Comment by almanshow** [comment]
This is what I got after running your code:

REQUEST:v3/accounts/101-004-5535280-002/trades
---------------------------------------------------------------------------
V20Error                                  Traceback (most recent call last)
<ipython-input-38-519f1964fc84> in <module>()
      9 try:
---> 10     rv = api.request(r)
     11 except V20Error as err:

C:\Users\user\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in request(self, endpoint)
    305             response = self.__request(method, url,
--> 306                                       request_args, headers=headers)
    307             content = response.content.decode('utf-8')

C:\Users\user\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py in __request(self, method, url, request_args, headers, stream)
    242             raise V20Error(response.status_code,
--> 243                            response.content.decode('utf-8'))
    244         return response

V20Error: 

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-38-519f1964fc84> in <module>()
      9 try:
     10     rv = api.request(r)
---> 11 except V20Error as err:
     12     print("ERROR: {}".format(err))
     13 else:

NameError: name 'V20Error' is not defined

**Comment by hootnot** [comment]
sorry, please import the V20Error:
```python
from oandapyV20.exceptions import V20Error
```

**Comment by almanshow** [comment]
It returned:"
ERROR:

".

**Comment by hootnot** [comment]
and the **curl** command ?

**Comment by almanshow** [comment]
What should I do in curl?

**Comment by hootnot** [comment]
perform the API request as I gave it in the earlier comment. Just fill in the TOK and ACCT variables and run it as a shell script or directly from the commandline

**Comment by almanshow** [comment]
Still makes me the same error.

**Comment by hootnot** [comment]
that is not possible, **curl** has nothing to do with the python. 
Check the OANDA docs http://developer.oanda.com/rest-live-v20/trade-ep/#collapse_2_example_curl_1 for an example too. 
If you don't have it please install it and run it.

If curl fails you definitely have an auth issue regarding your token/account. So I would like to exclude that.

**Comment by hootnot** [comment]
Another option: activate logging in DEBUG mode. You should get details how communication with oanda takes place.


```python
import json
from oandapyV20 import API
from oandapyV20.exceptions import V20Error
import oandapyV20.endpoints.trades as trades
import logging

api = API(access_token="...")
accountID = "xxx-yyy-zzzzzz-abc"   # make sure this is a V20 account! and not a v1 account: 1234567

logging.basicConfig(
    filename="./sometest.log",
    level=logging.DEBUG,
    format='%(asctime)s [%(levelname)s] %(name)s : %(message)s',
)
logger = logging.getLogger(__name__)

r = trades.TradesList(accountID)

print("REQUEST:{}".format(r))
try:
    rv = api.request(r)
except V20Error as err:
    print("ERROR: {}".format(err))
else:
    print("RESPONSE:\n{}".format(json.dumps(rv, indent=2)))
```
The output should show something like:
```text
2017-04-08 21:00:46,172 [INFO] oandapyV20.oandapyV20 : performing request https://api-fxpractice.oanda.com/v3/accounts/............./trades
2017-04-08 21:00:46,188 [DEBUG] requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): api-fxpractice.oanda.com
2017-04-08 21:00:47,059 [DEBUG] requests.packages.urllib3.connectionpool : https://api-fxpractice.oanda.com:443 "GET /v3/accounts/...................../trades HTTP/1.1" 200 40
```

**Comment by kevinwong15** [comment]
Hi Hootnot,

I revoked my token and regenerated a new one..

**Curl Command**
I tried the curl command and i was able to get output containing my account ID in the form
{"accounts":[{"id":"xxx-yyy-zzzzzzz-aaa","tags":[]}}

**Debug mode**
The following is the output I am getting from debug mode. 
As suggested, I get a 401 error which means I am unable to connect to the server.

`2017-04-11 22:47:35,043 [INFO] oandapyV20.oandapyV20 : performing request https://api-fxpractice.oanda.com/v3/accounts/xxx-yyy-aaaaaaa-bbb/trades
2017-04-11 22:47:35,043 [DEBUG] requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): api-fxpractice.oanda.com
2017-04-11 22:47:36,354 [DEBUG] requests.packages.urllib3.connectionpool : https://api-fxpractice.oanda.com:443 "GET /v3/accounts/001-011-1267575-003/trades HTTP/1.1" 401 0
2017-04-11 22:47:36,370 [ERROR] oandapyV20.oandapyV20 : request https://api-fxpractice.oanda.com/v3/accounts/001-011-1267575-003/trades failed [401,]`

**Comment by hootnot** [comment]
... this make no sense, one way (curl) allows you access and the python code not ?
Sounds like a typo in the token in that piece of code.

can you run:

```python
import urllib3   # maybe you need a: pip install urllib3

TOKEN = "<yourtoken>"

http = urllib3.PoolManager()
r = http.request(
    'GET',
    'https://api-fxpractice.oanda.com/v3/accounts',
    headers={
        'Authorization': 'Bearer {}'.format(TOKEN)
    })
print(r.status)
print(r.data.decode('utf-8'))
```

**Comment by kevinwong15** [comment]
Thanks for your help

**Comment by hootnot** [comment]
... is that  a confirmation of a typo in the token ?

**Comment by kevinwong15** [comment]
No, it is because I was using a token that is generated in my real account but I pointed this to the practice environment.

**Comment by hootnot** [comment]
the environment is `practice` by default. Make sure that you specify:`environment="live"` when you want to operate on your live-account.
Success with further coding!

**Comment by ZeroJitter** [comment]
Where exactly do I specify "environment=live" - I can authenticate and trade against fxpractice endpoints, however placing live credentials into ~/.v20.conf does not change the endpoints used from practice to live.

**Comment by hootnot** [comment]
@ZeroJitter you refer to ~/v20.conf ... so it looks like you use the v20 library of oanda since my lib, oandapyV20, does not use such a config file unless you wrote it yourself and made your code use it.

So if you use oandapyV20: see : http://oanda-api-v20.readthedocs.io/en/latest/oanda-api-v20.html#the-client for details.

Just pass it:

```python
client = API(access_token=..., environment="live")
```

If you use the v20 lib of oanda please check the docs of that library
