### ISSUE TITLE
trades.TradesList missing setting params attribute

### ISSUE THREAD

**Issue by mirac7** [hootnot/oanda-api-v20#69]
I believe there is a bug in `trades.TradesList` endpoint, in `__init__` method:

    class TradesList(Trades):
        def __init__(self, accountID, params=None):
            super(TradesList, self).__init__(accountID)
            self.params = params  # this line is missing

**Comment by hootnot** [comment]
@mirac7 Yup! you are right. Will you create the PR ?

**Comment by mirac7** [comment]
Created pull request

**Comment by hootnot** [comment]
Thx!
