### ISSUE TITLE
"Connection: Keep-Alive" question

### ISSUE THREAD

**Issue by silgon** [hootnot/oanda-api-v20#90]
This is more a question than an issue. It's about the best practices section of the developer references (http://developer.oanda.com/rest-live-v20/best-practices/).
They say that you should add a http header with the following content `Connection: Keep-Alive`. However I ran `grep -rn "Connection" .` in this repository and I found nothing. I would like to know if you consider this.

**Comment by hootnot** [comment]
hi @silgon 

That docs say also:
_If you are using an HTTP 1.0 client, ensure it supports the keep-alive directive and submit the header Connection: Keep-Alive with your request.

Keep-Alive is part of the protocol in HTTP 1.1 and enabled by default on compliant clients. However, you will have to ensure your implementation does not set the connection header to other values._

oandapyV20 makes use of  the _requests_ library and that does HTTP 1.1. Therefore it is not set.

**Comment by silgon** [comment]
Thanks for the reply! Just wanted to know. Nice library btw. =)

**Comment by hootnot** [comment]
thanks
