### ISSUE TITLE
Jupyter exampleAuth error

### ISSUE THREAD

**Issue by alexismanalo** [hootnot/oanda-api-v20#96]
I'm getting an error in this line of code under accounts.ipynb

```
import json
import oandapyV20
import oandapyV20.endpoints.accounts as accounts
from exampleauth import exampleauth

accountID, access_token = exampleauth.exampleAuth()
client = oandapyV20.API(access_token=access_token)

r = accounts.AccountList()
response = client.request(r)
print(json.dumps(response, indent=2))
```

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-ad842502edc9> in <module>()
>       2 import oandapyV20
>       3 import oandapyV20.endpoints.accounts as accounts
> ----> 4 from exampleauth import exampleauth
>       5 
>       6 accountID, access_token = exampleauth.exampleAuth()
> 
> ModuleNotFoundError: No module named 'exampleauth'
>

**Comment by hootnot** [comment]
Hi,

that class is in the oandapyV20-examples repo. I will take a look and see to update code and/or docs.
